### ISSUE TITLE
The Stop button doesn't work on test cases

### ISSUE THREAD

**Issue by matzagri** [TestCentric/testcentric-engine#39]
**Description**
Hello, 
I have a test project in which I am using a parameterized test method to which I am providing input using the TestCaseSource attribute. After I open the assembly containing my test in TestCentric I can see all the test cases but if I run them all (or just a subset) the Stop button does not work:

When clicking the button the execution does not stop when the current test case finishes; Furthermore, if I click the Kill button nothing happens. If I click the Kill button again the button becomes disabled, the test status changes to Failed and the UI freezes for a couple of seconds. Then the execution continues and at the end an exception occurs.

**Steps to reproduce the behavior:**
1. Load the TestCasesProject.dll from the attached folder into TestCentric
2. Click on Run All Tests
3. After a couple test cases pass click on the Stop button => the run doesn't stop
4. Click the Kill button => nothing happens
5. Click again the Kill button => the UI freezes for a couple of seconds, the test status changes to Failed and then the execution continues; an error appears at the end of the execution.

**Expected behavior**
When clicking the Stop button I expect the test execution to stop after the running test case ends.
When clicking the Kill button I expect the test execution to stop the running test case and the test execution.

**Environment:**
 - TestCentric Version 2.0.0-alpha4
 - OS: Windows 10
 - Target Runtime for your test assembly: .Net 5
 - Nunit Version 3.13.3
 - Nunit3TestAdapter Version 4.2.1

I attached a small project that can be used to reproduce the issue
[TestCasesProject.zip](https://github.com/TestCentric/testcentric-gui/files/8407774/TestCasesProject.zip)

**Comment by CharliePoole** [comment]
In the past, it has been the responsibility of the framework itself to cancel the test run when asked. With changes in .NET 5.0 and later, it's no longer possible to do this and the framework simply ignores `force: true`. See issue nunit/nunit#3276, which I filed in 2019.

In general, it's not possible for the engine  to know what a particular framework is capable of doing. However, such knowledge can (and should be) built into the driver for each framework it knows about, especially the NUnit V2 and 3 frameworks! So, in general, such knowledge belongs in a driver.

However, in this case, the engine runner should know that a forced stop is impossible under .NET 5.0 or greater, so this particular bit of knowledge could be built into the runner itself.

I'll experiment putting it in both places (runner and driver) and see which looks cleaner.

**Comment by CharliePoole** [comment]
Blocked while waiting to here how framework team plans to handle this issue.

**Comment by CharliePoole** [comment]
### Tasks:

This change is most readily tested using the GUI, which uses the engine package. So I'll do it as a series of small changes in separate PRs. Each PR will be merged and the GUI will be modified to use the new dev build. It's tedious but safe!

- [ ] Modify .NET Standard driver to throw an exception if `StopRun(true)` is called.

**Comment by CharliePoole** [comment]
It turns out that the Kill button stopped working, even for .NET Framework, in alpha 5. This is an additional problem on top of the one reported here, but it's moot anyway, since we'll be using `Process.Kill` for all frameworks.

**Comment by CharliePoole** [comment]
`StopRun(true)` in response to the Kill button was working in commit b85bec4, merged on April 17. Commit 1a49fbb broke it the following day. I've spent a bit of time on this and it's not easy to see exactly why. Since the plan is to re-implement `StopRun(true)` anyway, I'm not following up on the reasons for the failure any further.

**Comment by CharliePoole** [comment]
Normally, I'd save the UI for last. However, the Stop/Kill buttons in the GUI needed some fixes in order to make it easier to run manual tests, so i did the UI first.

**Comment by CharliePoole** [comment]
It's conceivable for a driver to handle `StopRun(true)` correctly. However, the plan at this point is to no longer expect any driver to do so. That simplifies things if we are cancelling a multi-assembly run with different drivers being used.

With that said, the approach I am implementing will work as follows...

1. Our built-in drivers will throw an exception if `StopRun(true)` is called. Note that we can't eliminate the argument because we make use of the nunit api, which includes it.

2. `AssemblyRunner` will terminate the process when the method is called. All other runners will continue to pass the call on to subordinate runners until `AssemblyRuner` is reached.

**Comment by matzagri** [comment]
Hello,

Thank you for working on this bug with a high priority. I'll check the behavior as soon as the alpha6 release is ready.
